server:
  port: 8083

spring:
  application:
    name: micros-3
  profiles:
    active: dev
  config:
    import: 'optional:configserver:http://localhost:8071'

management:
  endpoints:
    web:
      exposure:
        include: '*'
